config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: "/admin", controllers: {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords"}
  get 'welcome' => 'application#index'
  get 'about/:name' => "pages#about_me", as: "about_me"
  get 'contact/me' => "pages#contact"
  
  get "/login", to: redirect("/admin/sign_in")
  get "/admin", to: redirect("/admin/sign_in")
  
  resources :blogs, only: [:index, :show] do
    member do
     get 'update_like_or_dislike_count'
    end
    resources :comments
  end
  
  root to: "blogs#index"

  # Example resource route within a namespace:
   namespace :admin do
     # Directs /admin/products/* to Admin::ProductsController
     # (app/controllers/admin/products_controller.rb)
     resources :blogs do
       resources :comments, except: [:new, :create]
     end
     resources :dashboard, only: [:index]
   end
end

app/models/comment.rb
class Comment
  include Mongoid::Document
	include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  belongs_to :blog
    
  field :name, type: String
  field :desc, type: String

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_blog
  layout 'admin'
  
  def index
    @comments = @blog.comments.order("created_at desc").paginate(:page => params[:page], :per_page => 3)
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end
  
  def show
    @comment = Comment.find(params[:id])
  end
  
  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to admin_blog_comments_path(@blog), notice: "Updated Successfully!"
    else
      render action: "new"
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_blog_comments_path(@blog)
  end
  
  private
  def load_blog
    @blog = Blog.find(params[:blog_id])
  end
  
  def comment_params
    params.require(:comment).permit(:name, :desc, :blog_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        @comment = Comment.new
        format.html { redirect_to root_path, notice: 'Comment was successfully created.' }
        format.js { render layout: false }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :desc, :blog_id)
    end
end

app/views/admin/comments/edit.html.haml
%div
  %h3 Edit Comment
  = link_to "Back", admin_blog_comments_path(@blog), class: "btn btn-primary", style: "float:right;margin-top:-41px;"
%hr
= form_for @comment, url: admin_blog_comment_path(@blog, @comment), html: {class: "form-horizontal", method: "PUT"} do |f|
  .form-group
    %label.col-sm-2.control-label{:for => "Title"} *Name
    .col-sm-10
      = f.text_field :name, placeholder: "Commentor name", class: "form-control"
  .form-group
    %label.col-sm-2.control-label *Content
    .col-sm-10
      = f.cktext_area :desc, placeholder: "Comments", class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      %button.btn.btn-primary{:type => "submit"} Update
      

app/views/admin/comments/index.html.haml
.container-fluid
  .row
    .col-lg-12
      %div
        %h2 Blog Comments
        = link_to "Back", admin_blogs_path, class: "btn btn-primary", style: "float:right;margin-top:-41px;"
      %hr
      %h4
        Blog Title:
        = link_to @blog.title, admin_blog_path(@blog)
      %table.table.table-hover
        %thead
          %tr
            %th Commentor Name
            %th Comment
            %th Posted At
            %th
        %tbody
          - @comments.each do |comment|
            %tr
              %td= comment.name
              %td= comment.desc
              %td
                = time_ago_in_words(comment.created_at) 
                ago
              %td
                = link_to "View", admin_blog_comment_path(@blog, comment), class: "btn btn-primary"
                = link_to "Edit", edit_admin_blog_comment_path(@blog, comment), class: "btn btn-default"
                = link_to "Remove", admin_blog_comment_path(@blog, comment), method: :delete, class: "btn btn-danger" 
                
                
      = will_paginate @comments   

app/views/admin/comments/show.html.haml
%div
  %h3= @blog.title
  = link_to "Back", admin_blog_comments_path(@blog), class: "btn btn-primary", style: "float:right;margin-top:-41px;"
%hr

.container-fluid
  .row
    .col-lg-12
      %h4 Comment
      %div
        %label Commentor Name:
        %p= @comment.name
      %div
        %label Content:
        %p= @comment.desc         
      %div
        %label Created At:
        %p= @comment.created_at.strftime("%d %b, %Y %H:%M")   
        
= link_to "Edit", edit_admin_blog_comment_path(@blog, @comment), class: "btn btn-default"