config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: "/admin", controllers: {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords"}
  get 'welcome' => 'application#index'
  get 'about/:name' => "pages#about_me", as: "about_me"
  get 'contact/me' => "pages#contact"
  
  get "/login", to: redirect("/admin/sign_in")
  get "/admin", to: redirect("/admin/sign_in")
  
  resources :blogs, only: [:index, :show] do
    member do
     get 'update_like_or_dislike_count'
    end
    resources :comments
  end
  
  root to: "blogs#index"

  # Example resource route within a namespace:
   namespace :admin do
     # Directs /admin/products/* to Admin::ProductsController
     # (app/controllers/admin/products_controller.rb)
     resources :blogs do
       resources :comments, except: [:new, :create]
     end
     resources :dashboard, only: [:index]
   end
end

app/models/blog.rb
class Blog
  include Mongoid::Document
	include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  
  belongs_to :user
  has_many :comments, dependent: :destroy

  field :title,        type: String
  field :content,      type: String
  field :tags,         type: Array, default: []
  field :is_active,    type: Boolean, default: true
  field :likes,        type: Integer, default: 0
  field :dislikes,     type: Integer, default: 0
  field :views,        type: Integer, default: 0
 
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
 
  def tags_list=(arg)
    self.tags = arg.split(',').map { |v| v.strip.titleize }
  end

  def tags_list
    self.tags.join(', ')
  end
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
  
  def index
    @blogs = Blog.all.order("created_at desc") #.paginate(:page => params[:page], :per_page => 10)
  end
  
  def new
    @blog = current_user.blogs.new
  end
  
  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to admin_blogs_path, notice: "Posted Successfully!"
    else
      render action: "new"
    end
  end
  
  def edit
    @blog = Blog.find(params[:id])
  end
  
  def show
      @blog = Blog.find(params[:id])
  end
  
  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to admin_blogs_path, notice: "Post Updated Successfully!"
    else
      render action: "new"
    end
  end
  
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to admin_blogs_path
  end
  
  private
  def load_blog
    @blog = Blog.find(params[:id])
  end
  
  def blog_params
    params.require(:blog).permit(:title, :content, :tags, :tags_list, :user_id, :is_active, :created_at, :updated_at)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :update_like_or_dislike_count]
  
  def index
    scope = Blog
    if params[:tag].present?
      scope = scope.where(tags: params[:tag].titleize)
    end  
    @blogs = scope.order("created_at desc").paginate(:page => params[:page], :per_page => 10)
  end
  
  
  def show
    session[:viewed] ||= []
    @blog = Blog.find(params[:id])
    @comment = Comment.new  
    @blog_comments = @blog.comments
    unless session[:viewed].include?(@blog.id.to_s)
      session[:viewed] << @blog.id.to_s
      @blog.update_attribute(:views, (@blog.views + 1))
    end
    render layout: "blog"
  end
  
  def update_like_or_dislike_count
    @blog = Blog.find(params[:id])
    session[:liked] ||= []
    session[:disliked] ||= []
    case params[:type]
      when "like"
        unless session[:liked].include?(@blog.id.to_s)
          session[:liked] << @blog.id.to_s
          @blog.update_attribute(:likes, (@blog.likes + 1))
        end  
      when "dislike"
        unless session[:disliked].include?(@blog.id.to_s)
          session[:disliked] << @blog.id.to_s
          @blog.update_attribute(:dislikes, (@blog.dislikes + 1))
        end 
    end
    respond_to do |format|
      format.html { redirect_to blog_path(@blog) }
      format.js { render layout: false }
    end
  end
  
  
  private
  def load_blog
    @blog = Blog.find(params[:id])
  end
  
  def blog_params
    params.require(:blog).permit(:title, :content, :tags, :tags_list, :user_id, :is_active)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_comments.html.haml
%h3 
  Comments
  (
  = @blog.comments.count rescue 0
  )
%hr

.col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
  .new_comment
    %h4 Please comment here
    = form_for @comment, url: blog_comments_path(@blog), html: {method: "POST", remote: "true", class: "form-horizontal"} do |f|
      .form-group
        %label.col-sm-2.control-label Your Name
        .col-sm-10
          = f.text_field :name, placeholder: "Please enter your name", class: "form-control"
      .form-group
        %label.col-sm-2.control-label Your Comments
        .col-sm-10
          = f.text_area :desc, placeholder: "Enter your comments here...", rows: "6", class: "form-control"
      
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.submit "Submit Comment".html_safe, class: "btn btn-success btn-circle text-uppercase"
  
  %br
  %br
  - if @blog.comments.present?
    %section.comments_list
      - @blog.comments.order("created_at DESC").each do |comment|
        %article.comment
          %a.comment-img{:href => "#non"}
            = image_tag("avatar_2x.png", height: "50", width: "50", title: "#{comment.name}")
          .comment-body
            .text
              %p= comment.desc.html_safe rescue nil
            %p.attribution
              by
              %a{:href => "#non"}
                = comment.name.present? ? comment.name.titleize : "Anonymous"
              at
              = comment.created_at #.strftime("%H:%M %d %b, %Y")

app/views/blogs/_likemenu.html.haml
%p= link_to "<span>(#{@blog.likes})</span>".html_safe, update_like_or_dislike_count_blog_path(@blog, type: "like"), remote: true, class: "like"
%p= link_to "<span>(#{@blog.dislikes})</span>".html_safe, update_like_or_dislike_count_blog_path(@blog, type: "dislike"), remote: true, class: "dislike"

app/views/blogs/index.html.haml
= content_for(:heading, "Venkata Kishor M")
= content_for(:sub_heading, "A Professional Ruby on Rails Guy.")
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      - @blogs.each do |blog|
        .post-preview
          %a{:href => blog_path(blog)}
            %h2.post-title
              = blog.title
              
          %p.post-meta
            Posted by
            %a{:href => "#"}= blog.user.email
            on
            = blog.created_at.strftime("%B %d, %Y")
        %hr/
      
     
      %ul.pager
        %li.next
          = will_paginate @blogs
%hr/

app/views/blogs/show.html.haml
= content_for(:heading, @blog.title)
= content_for(:sub_heading, "Posted #{time_ago_in_words(@blog.created_at)} ago")
= content_for(:views, "Page Views: #{@blog.views}")

%article
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        .blog-content
          = @blog.content.html_safe
        %br
        - if @blog.tags.present?
          .tags
            %h5 Tags:
            %hr
            - @blog.tags.each do |tag|
              = link_to tag, blogs_path(tag: tag), class: "btn", style: "color:#fff;padding: 6px 25px;background:grey;"
        
    %br            
    .row.comments
      = render "comments", blog: @blog, comment: @comment

%a.backtohome{:href => "/"}
  %i.fa.fa-angle-up
  << Back to Home 

 
.likemenu
  = render 'likemenu', blog: @blog

app/views/blogs/update_like_or_dislike_count.js.erb
$(".likemenu").html("<%= escape_javascript(render :partial => '/blogs/likemenu', :locals => { blog: @blog }) %>");